version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
